version: "3.10"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=poolit_db
      - POSTGRES_USER=poolit_assgn
      - POSTGRES_PASSWORD=test123

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: grand_auctions
    volumes:
      - .:/auctions
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - POSTGRES_DB=poolit_db
      - POSTGRES_USER=poolit_assgn
      - POSTGRES_PASSWORD=test123
    depends_on:
      - db
